version: '3.8'
services:
  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    ports:
      - 8080:8080
    networks:
      - node-network

  music_catalog_service:
    container_name: music_catalog_service
    build: ./music_catalog_service
    environment:
      - DATABASE_URL=postgresql://postgres:1234@some-postgres:5432/db_spotify
      - REDIS_HOST=some-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1234
      - REDIS_TTL=3600
    networks:
      - node-network

  playlist_service:
    container_name: playlist_service
    build: ./playlist_service
    environment:
      - DATABASE_URL=postgresql://postgres:1234@some-postgres:5432/db_spotify
      - JWT_SECRET=0c6de6e71051d454627fca4b8728c97111791251b71d00f20091d357600d934543eb97f8dda314a3ed596d239c5dd4e5971bf9661eb8a29f6bde5cf51b7afe1a
    networks:
      - node-network

  social_service:
    container_name: social_service
    build: ./social_service
    environment:
      - DATABASE_URL=postgresql://postgres:1234@some-postgres:5432/db_spotify
      - JWT_SECRET=0c6de6e71051d454627fca4b8728c97111791251b71d00f20091d357600d934543eb97f8dda314a3ed596d239c5dd4e5971bf9661eb8a29f6bde5cf51b7afe1a
      - REDIS_HOST=some-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1234
      - REDIS_TTL=3600
    networks:
      - node-network

  user_service:
    container_name: user_service
    build: ./user_service
    environment:
      - DATABASE_URL=postgresql://postgres:1234@some-postgres:5432/db_spotify
      - JWT_SECRET=0c6de6e71051d454627fca4b8728c97111791251b71d00f20091d357600d934543eb97f8dda314a3ed596d239c5dd4e5971bf9661eb8a29f6bde5cf51b7afe1a
    networks:
      - node-network

networks:
  node-network:
    external: true
    